<?php

namespace ContainerBCsFVgJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AdminAuthenticator' shared autowired service.
     *
     * @return \App\Security\AdminAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\AdminAuthenticator'])) {
            return $container->privates['App\\Security\\AdminAuthenticator'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\Security\\AdminAuthenticator'])) {
            return $container->privates['App\\Security\\AdminAuthenticator'];
        }
        $c = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Security\\AdminAuthenticator'])) {
            return $container->privates['App\\Security\\AdminAuthenticator'];
        }

        return $container->privates['App\\Security\\AdminAuthenticator'] = new \App\Security\AdminAuthenticator($a, $b, $c);
    }
}
