<?php

namespace ContainerBCsFVgJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAfterEntityPersistedEventService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.vUennKN.EasyCorp\Bundle\EasyAdminBundle\Event\AfterEntityPersistedEvent' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Event\AfterEntityPersistedEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vUennKN": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent" but no such service exists.');
    }
}
