<?php

namespace ContainerBCsFVgJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnseigneCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\EnseigneCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\EnseigneCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['App\\Controller\\Admin\\EnseigneCrudController'])) {
            return $container->services['App\\Controller\\Admin\\EnseigneCrudController'];
        }
        $b = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->services['App\\Controller\\Admin\\EnseigneCrudController'])) {
            return $container->services['App\\Controller\\Admin\\EnseigneCrudController'];
        }

        $container->services['App\\Controller\\Admin\\EnseigneCrudController'] = $instance = new \App\Controller\Admin\EnseigneCrudController($a, $b);

        $instance->setContainer(($container->privates['.service_locator.3YFBJbt'] ?? $container->load('get_ServiceLocator_3YFBJbtService'))->withContext('App\\Controller\\Admin\\EnseigneCrudController', $container));

        return $instance;
    }
}
