knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
            user_fields: ['profile', 'email']
            redirect_uri: 'https://karabs-backend1.up.railway.app/connect/google/check'