<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '5a60fbf20b1a276ca2a0a2a50b6fae57',
  'DATABASE_URL' => 'mysql://root:rootroot@127.0.0.1:3306/karabs_6?serverVersion=8.0&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://yasserrazzaki0@gmail.com:jrilkzmwmvutyqju@smtp.gmail.com:587?encryption=tls',
  'MAILER_FROM_ADDRESS' => 'yasserrazzaki0@gmail.com',
  'MAILER_FROM_NAME' => 'Le Karabs App',
  'GOOGLE_CLIENT_ID' => '302695246353-sjckld4s69csqlq6guvl7j1s29pphs2c.apps.googleusercontent.com',
  'GOOGLE_CLIENT_SECRET' => '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',
  'FRONTEND_URL' => 'http://localhost:8100',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '1c0d4d6861f92abcb81b77749603add5e43b840238a206cb5810137012f3471d',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
