<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '5a60fbf20b1a276ca2a0a2a50b6fae57',
  'DATABASE_URL' => 'mysql://root:IIaFkCbgVYaDiVtmpIvqMDKtZWsgfHyC@centerbeam.proxy.rlwy.net:30799/railway',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://yasserrazzaki0@gmail.com:jrilkzmwmvutyqju@smtp.gmail.com:587?encryption=tls',
  'MAILER_FROM_ADDRESS' => 'yasserrazzaki0@gmail.com',
  'MAILER_FROM_NAME' => 'Le Karabs App',
  'GOOGLE_CLIENT_ID' => '302695246353-43jqkl03ncpqe1dua62n9n0ulq4nf5ns.apps.googleusercontent.com',
  'GOOGLE_CLIENT_SECRET' => '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',
  'FRONTEND_URL' => 'https://karabs-front.vercel.app',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '1c0d4d6861f92abcb81b77749603add5e43b840238a206cb5810137012f3471d',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1|karabs-front\\.vercel\\.app)(:[0-9]+)?$',
);
