<?php

namespace ContainerKRMYERO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Security_RequestMatcher_5eRZPSiService extends App_KernelProdContainer
{
    /*
     * Gets the private '.security.request_matcher.5eRZPSi' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\ChainRequestMatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.security.request_matcher.5eRZPSi'] = new \Symfony\Component\HttpFoundation\ChainRequestMatcher([($container->privates['.security.request_matcher.obhk0jm'] ??= new \Symfony\Component\HttpFoundation\RequestMatcher\PathRequestMatcher('^/admin'))]);
    }
}
