<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRMYERO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRMYERO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKRMYERO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKRMYERO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKRMYERO\App_KernelProdContainer([
    'container.build_hash' => 'KRMYERO',
    'container.build_id' => '77cc1033',
    'container.build_time' => 1748635571,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRMYERO');
