<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAM7llsa\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAM7llsa/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAM7llsa.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAM7llsa\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAM7llsa\App_KernelProdContainer([
    'container.build_hash' => 'AM7llsa',
    'container.build_id' => '9379a49d',
    'container.build_time' => 1748606392,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAM7llsa');
