<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2LYzk6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2LYzk6/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerF2LYzk6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerF2LYzk6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerF2LYzk6\App_KernelProdContainer([
    'container.build_hash' => 'F2LYzk6',
    'container.build_id' => '3e4a68b1',
    'container.build_time' => 1748634355,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2LYzk6');
