<?php

namespace ContainerPxIUI0L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3hTzNyoService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.3hTzNyo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3hTzNyo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actions' => ['privates', '.errored.ukCdkfE', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::configureActions()": the $actions argument is type-hinted with the non-existent class or interface: "App\\Controller\\Actions". Did you forget to add a use statement?'],
        ], [
            'actions' => '?',
        ]);
    }
}
