<?php

namespace Container0LCfUT2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_AdminService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.admin' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.manager.admin'] ?? $container->load('getSecurity_Authenticator_Manager_AdminService'));

        if (isset($container->privates['security.firewall.authenticator.admin'])) {
            return $container->privates['security.firewall.authenticator.admin'];
        }

        return $container->privates['security.firewall.authenticator.admin'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener($a);
    }
}
