<?php

namespace ContainerF2LYzk6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E7H7EwService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.e7H7Ew_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e7H7Ew_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.e7H7Ew_.EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityDeletedEvent', NULL, 'Cannot autowire service ".service_locator.e7H7Ew_": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityDeletedEvent" but no such service exists.'],
        ], [
            'event' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityDeletedEvent',
        ]);
    }
}
