<?php

namespace ContainerF2LYzk6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoraireTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\HoraireType' shared autowired service.
     *
     * @return \App\Form\HoraireType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\HoraireType'] = new \App\Form\HoraireType();
    }
}
