<?php

namespace ContainerF2LYzk6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NotationRepository' shared autowired service.
     *
     * @return \App\Repository\NotationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NotationRepository'] = new \App\Repository\NotationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
