<?php

namespace ContainerAM7llsa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VUennKNService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.vUennKN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vUennKN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.vUennKN.EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent', NULL, 'Cannot autowire service ".service_locator.vUennKN": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent" but no such service exists.'],
        ], [
            'event' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Event\\AfterEntityPersistedEvent',
        ]);
    }
}
