<?php

namespace ContainerAM7llsa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBeforeEntityDeletedEventService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.e7H7Ew_.EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityDeletedEvent' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Event\BeforeEntityDeletedEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.e7H7Ew_": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Event\\BeforeEntityDeletedEvent" but no such service exists.');
    }
}
