<?php

namespace ContainerAM7llsa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoraireRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\HoraireRepository' shared autowired service.
     *
     * @return \App\Repository\HoraireRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\HoraireRepository'] = new \App\Repository\HoraireRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
