<?php

namespace ContainerAM7llsa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\OAuthAuthenticator' shared autowired service.
     *
     * @return \App\Security\OAuthAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\OAuthAuthenticator'])) {
            return $container->privates['App\\Security\\OAuthAuthenticator'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\Security\\OAuthAuthenticator'])) {
            return $container->privates['App\\Security\\OAuthAuthenticator'];
        }
        $c = ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService'));

        if (isset($container->privates['App\\Security\\OAuthAuthenticator'])) {
            return $container->privates['App\\Security\\OAuthAuthenticator'];
        }

        return $container->privates['App\\Security\\OAuthAuthenticator'] = new \App\Security\OAuthAuthenticator(($container->services['knpu.oauth2.registry'] ??= new \KnpU\OAuth2ClientBundle\Client\ClientRegistry($container, ['google' => 'knpu.oauth2.client.google'])), $a, $b, $c);
    }
}
