<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsW6n4G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsW6n4G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsW6n4G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsW6n4G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMsW6n4G\App_KernelDevDebugContainer([
    'container.build_hash' => 'MsW6n4G',
    'container.build_id' => '32257b67',
    'container.build_time' => 1748204390,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsW6n4G');
