<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Enseigne extends \App\Entity\Enseigne implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'favoris' => [parent::class, 'favoris', null, 16],
        "\0".parent::class."\0".'horaires' => [parent::class, 'horaires', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'latitude' => [parent::class, 'latitude', null, 16],
        "\0".parent::class."\0".'longitude' => [parent::class, 'longitude', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'notations' => [parent::class, 'notations', null, 16],
        "\0".parent::class."\0".'noteAmbiance' => [parent::class, 'noteAmbiance', null, 16],
        "\0".parent::class."\0".'notePrix' => [parent::class, 'notePrix', null, 16],
        "\0".parent::class."\0".'noteQualite' => [parent::class, 'noteQualite', null, 16],
        "\0".parent::class."\0".'numeroTelephone' => [parent::class, 'numeroTelephone', null, 16],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null, 16],
        "\0".parent::class."\0".'pointsCle' => [parent::class, 'pointsCle', null, 16],
        "\0".parent::class."\0".'slogan' => [parent::class, 'slogan', null, 16],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'favoris' => [parent::class, 'favoris', null, 16],
        'horaires' => [parent::class, 'horaires', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'latitude' => [parent::class, 'latitude', null, 16],
        'longitude' => [parent::class, 'longitude', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'notations' => [parent::class, 'notations', null, 16],
        'noteAmbiance' => [parent::class, 'noteAmbiance', null, 16],
        'notePrix' => [parent::class, 'notePrix', null, 16],
        'noteQualite' => [parent::class, 'noteQualite', null, 16],
        'numeroTelephone' => [parent::class, 'numeroTelephone', null, 16],
        'photo' => [parent::class, 'photo', null, 16],
        'pointsCle' => [parent::class, 'pointsCle', null, 16],
        'slogan' => [parent::class, 'slogan', null, 16],
        'website' => [parent::class, 'website', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
