<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Horaire extends \App\Entity\Horaire implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'enseigne' => [parent::class, 'enseigne', null, 16],
        "\0".parent::class."\0".'heureFermeture' => [parent::class, 'heureFermeture', null, 16],
        "\0".parent::class."\0".'heureOuverture' => [parent::class, 'heureOuverture', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'jour' => [parent::class, 'jour', null, 16],
        'enseigne' => [parent::class, 'enseigne', null, 16],
        'heureFermeture' => [parent::class, 'heureFermeture', null, 16],
        'heureOuverture' => [parent::class, 'heureOuverture', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'jour' => [parent::class, 'jour', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
